root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./temp/app ./*.go"
bin = "./temp/app"
delay = 2000
include_ext = ["go"]
include_dir = ["cmd", "internal", "frontend"]
exclude_regex = ["_test.go$", "_gen.go$"]
stop_on_error = true

[log]
main_only = true
